export {default as Loader} from './Loader'
export {default as Navebar} from './Navebar'
export {default as Services} from './Services'
export {default as Transections} from './Transections'
export {default as Welcome} from './Welcome'
export {default as Footer} from './Footer'